name: Build and Release SystemInfo Tweak

on:
  workflow_dispatch: # Manual trigger

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Homebrew
      run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        brew update

    - name: Install Theos Dependencies (Homebrew)
      run: |
        brew install ldid git zip dpkg # These are examples, adjust as needed!

    - name: Set up Theos
      run: |
        git clone --recursive https://github.com/theos/theos.git $HOME/theos
        echo "THEOS_MAKE_PATH=$HOME/theos/makefiles" >> $GITHUB_ENV
        echo "THEOS=$HOME/theos" >> $GITHUB_ENV
        export THEOS=$HOME/theos
        export THEOS_MAKE_PATH=$HOME/theos/makefiles
        
    - name: Build Tweak
      run: |
        export SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk
        make package THEOS_PLATFORM_NAME=ios

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: ./packages/*.deb
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}