name: Build and Release Tweak

on:
  workflow_dispatch: # Manual trigger
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          brew update
          brew install ldid dpkg Logos

      - name: Set up Keychain and Files
        run: |
          mkdir -p build_dir
          chmod 777 build_dir
          cp CMDX.sh control entitlements.plist BDG.p12 build_dir
          cp CPUInfoProvider.swift FloatingButton.swift InfoWindow.swift MemoryInfoProvider.swift SystemInfo.swift build_dir
          cp Tweak.x build_dir
          cd build_dir
          echo "BDG" > p12_password.txt

      - name: Build Tweak
        run: |
          cd build_dir
          bash CMDX.sh

      - name: List build_dir contents
        run: |
          ls -la build_dir

      - name: Zip build_dir
        run: |
          cd build_dir
          zip -r build_dir.zip .

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: build_dir/build_dir.zip
          tag_name: Beta # Set the tag name to Beta
          name: Beta # Set the release name to Beta
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}