name: Build and Release SystemInfo Tweak

on:
  workflow_dispatch: # Manual trigger

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Theos
      run: |
        #  Install Theos dependencies (you might need to adjust this)
        sudo apt-get update
        sudo apt-get install ldid git zip dpkg-dev

        git clone --recursive https://github.com/theos/theos.git $HOME/theos
        echo "THEOS_MAKE_PATH=$HOME/theos/makefiles" >> $GITHUB_ENV
        echo "THEOS=$HOME/theos" >> $GITHUB_ENV
        export THEOS=$HOME/theos
        export THEOS_MAKE_PATH=$HOME/theos/makefiles
        
    - name: Build Tweak
      run: |
        export SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk
        make package THEOS_PLATFORM_NAME=ios

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: ./packages/*.deb
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}