name: Build SystemInfo Tweak

on:
  workflow_dispatch: # Allows manual triggering from the Actions tab on GitHub

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Theos
      run: |
        #  Install Theos dependencies (you might need to adjust this)
        sudo apt-get update
        sudo apt-get install ldid git zip dpkg-dev

        git clone --recursive https://github.com/theos/theos.git $HOME/theos
        echo "THEOS_MAKE_PATH=$HOME/theos/makefiles" >> $GITHUB_ENV
        echo "THEOS=$HOME/theos" >> $GITHUB_ENV
        export THEOS=$HOME/theos
        export THEOS_MAKE_PATH=$HOME/theos/makefiles
        
    - name: Build Tweak
      run: |
        export SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk
        make package THEOS_PLATFORM_NAME=ios

    - name: Upload .deb artifact
      uses: actions/upload-artifact@v3
      with:
        name: systeminfo-tweak
        path: ./packages/*.deb