name: Build, Package, and Release Tweak

on:
  push:
    branches:
      - main  # Change this to your main branch if different
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Theos
      run: |
        git clone https://github.com/theos/theos.git $HOME/theos
        echo "export THEOS=$HOME/theos" >> $GITHUB_ENV
        echo "export PATH=$HOME/theos/bin:$PATH" >> $GITHUB_ENV

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y dpkg fakeroot ldid gnu-tar || echo "Installation of ldid or gnu-tar failed"
        sudo apt-get clean

    - name: Build tweak
      run: make package

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.run_number }}
        release_name: Release v${{ github.run_number }}
        draft: false
        prerelease: false

    - name: Upload Package to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./packages/*.deb
        asset_name: cpuinfooverlay.deb
        asset_content_type: application/octet-stream