name: Build iOS dylib on macOS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: 'latest-stable'

    - name: Set up Theos
      run: |
        git clone --depth 1 https://github.com/theos/theos.git $HOME/theos
        echo "THEOS=$HOME/theos" >> $GITHUB_ENV
        echo "$HOME/theos/bin:$PATH" >> $GITHUB_PATH
        echo "THEOS_MAKE_PATH=$HOME/theos/makefiles" >> $GITHUB_ENV
        # Set SDKROOT and THEOS_PLATFORM_NAME for iOS
        echo "SDKROOT=$(xcodebuild -version -sdk iphoneos Path)" >> $GITHUB_ENV
        echo "THEOS_PLATFORM_NAME=iphoneos" >> $GITHUB_ENV

    - name: Install dependencies
      run: |
        brew update
        brew install dpkg
        # Assuming ldid is needed for signing
        curl -LO https://github.com/ProcursusTeam/ldid/releases/download/v2.1.5-procursus7/ldid_macosx_x86_64
        sudo install -m 755 ldid_macosx_x86_64 /usr/local/bin/ldid

    - name: Verify dependencies installation
      run: |
        dpkg --version || { echo "Failed to verify dpkg"; exit 1; }
        ldid -h || { echo "Failed to verify ldid"; exit 1; }

    - name: Build dylib
      run: |
        make || { echo "Build failed"; exit 1; }

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.run_number }}-${{ github.sha }}
        release_name: Release v${{ github.run_number }}-${{ github.sha }}
        draft: false
        prerelease: false

    - name: Upload Package to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./${{ github.workspace }}/packages/*.dylib
        asset_name: SystemInfo_${{ github.run_number }}.dylib
        asset_content_type: application/octet-stream